### ISSUE TITLE
Test suite depends on specific directory structure, doesn't always exist

### ISSUE THREAD

**Issue by snoyberg** [IreneKnapp/direct-sqlite#60]
Steps to reproduce:
1. `stack unpack direct-sqlite`
2. `cd direct-sqlite-*`
3. `stack init`
4. `stack test`

Output:

```
Creating dist/test/direct-sqlite-test-database.db
test: SQLite3 returned ErrorCan'tOpen while attempting to perform open "dist/test/direct-sqlite-test-database.db": unable to open database file

Completed 2 action(s).
Test suite failure for package direct-sqlite-2.3.16
    test:  exited with: ExitFailure 1
Logs printed to console
```

This is not a Stack-specific issue, it was originally discovered via the Stackage build process, which calls out to the Setup.hs file directly.

**Comment by nurpax** [comment]
Thanks for the bug report @snoyberg, I'll take a look!

**Comment by nurpax** [comment]
@snoyberg Do you have any recommendation on what to use instead of "dist/test"?

I looked at the module Paths_pkgname but that doesn't specify any sort of a temp directory like the build directory that could be used here.

As the test creates the temp db file and deletes it after the test has run (even under exceptions) , I wonder if it'd be ok to just use "./" instead of "./dist/test"?  Or maybe use System.IO.Temp.withTempDirectory?

**Comment by snoyberg** [comment]
I would definitely recommend withTempDirectory

**Comment by nurpax** [comment]
@snoyberg direct-sqlite-2.3.17 should fix this.
